# Generated by Django 5.1.4 on 2024-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
    ]
