# Generated by Django 5.1.4 on 2024-12-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_description_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='defaultpassword123', max_length=100),
        ),
    ]
