# Generated by Django 5.1.4 on 2024-12-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_votingtimeframe_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='blockchain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
