# Generated by Django 5.1.4 on 2025-01-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidAdmissionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
